### ISSUE TITLE
Error session message for login and registration

### ISSUE THREAD

**Issue by vctr-dng** [overleaf/toolkit#151]
Hi,

I have attempted to install overleaf using the toolkit on Ubuntu server 22.04. However when I am trying to login or register I have the following error :
Session error. Please check you have cookies enabled. If the problem persists, try clearing your cache and cookies.

## Steps to Reproduce

1. I followed the [Quick-Start Guide](https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md) step by step up until "Create the first admin account" section.
2. From my laptop I tried to connect on http://192.168.0.128/launchpad (192.168.0.128 is the local IP of my ubuntu server) however I couldn't connect to it.
3. I followed [TLS Proxy for Overleaf Toolkit environment](https://github.com/overleaf/toolkit/blob/master/doc/tls-proxy.md).
4. However when running **bin/up** I had some error about port 80 being bind
5. I disabled the TLS feature and changed *SHARELATEX_LISTEN_IP* to the ubuntu local IP in **overleaf.rc**.
6. I could finally connect to http://192.168.0.128/launchpad

## Expected Behaviour

Registration should work.
Login should send another error

## Observed Behaviour

When I am trying to login or register I have the following error :
Session error. Please check you have cookies enabled. If the problem persists, try clearing your cache and cookies.

## Analysis

I have tried to register on my laptop and my phone.

### Overleaf doctor

```
====== Overleaf Doctor ======
- Host Information
    - Linux
    - Output of 'lsb_release -a':
            No LSB modules are available.
            Distributor ID:	Ubuntu
            Description:	Ubuntu 22.04.2 LTS
            Release:	22.04
            Codename:	jammy
- Dependencies
    - bash
        - status: present
        - version info: 5.1.16(1)-release
    - docker
        - status: present
        - version info: Docker version 23.0.4, build f480fb1
    - docker-compose
        - status: present
        - version info: docker-compose version 1.29.2, build unknown
    - realpath
        - status: present
        - version info: realpath (GNU coreutils) 8.32
    - perl
        - status: present
        - version info: 5.034000
    - awk
        - status: present
        - version info: GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)
    - openssl
        - status: present
        - version info: OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
- Docker Daemon
    - status: up
====== Configuration ======
- config/version
    - status: present
    - version: 3.5.5
- config/overleaf.rc
    - status: present
    - values
        - SHARELATEX_DATA_PATH: data/sharelatex
        - SERVER_PRO: false
        - SHARELATEX_LISTEN_IP: 192.168.0.128
        - SHARELATEX_PORT: 80
        - MONGO_ENABLED: true
        - MONGO_IMAGE: mongo:4.4
        - MONGO_DATA_PATH: data/mongo
        - REDIS_ENABLED: true
        - REDIS_DATA_PATH: data/redis
        - NGINX_ENABLED: false
        - NGINX_CONFIG_PATH: config/nginx/nginx.conf
        - TLS_PRIVATE_KEY_PATH: config/nginx/certs/overleaf_key.pem
        - TLS_CERTIFICATE_PATH: config/nginx/certs/overleaf_certificate.pem
        - NGINX_HTTP_LISTEN_IP: 192.168.0.128
        - NGINX_HTTP_PORT: 80
        - NGINX_TLS_LISTEN_IP: 192.168.0.128
        - TLS_PORT: 443
        - GIT_BRIDGE_ENABLED: false
- config/variables.env
    - status: present
    - values
        - SHARELATEX_FILESTORE_BACKEND: fs
        - SHARELATEX_HISTORY_BACKEND: fs
====== Warnings ======
- None, all good
====== End ======
```

### Logs inside the container

I enable logging for every container possible and the web sends this when trying to register : 
```
{"name":"web","hostname":"ce725d8ab355","pid":139,"level":40,"err":{"message":"invalid csrf token","name":"ForbiddenError","stack":"ForbiddenError: invalid csrf token
    at csrf (/overleaf/node_modules/csurf/index.js:112:19)
    at Csrf.middleware (/overleaf/services/web/app/src/infrastructure/Csrf.js:79:14)
    at Layer.handle [as handle_request] (/overleaf/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/overleaf/node_modules/express/lib/router/index.js:328:13)
    at /overleaf/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/overleaf/node_modules/express/lib/router/index.js:346:12)
    at next (/overleaf/node_modules/express/lib/router/index.js:280:10)
    at SessionStrategy.strategy.pass (/overleaf/node_modules/passport/lib/middleware/authenticate.js:343:9)
    at SessionStrategy.authenticate (/overleaf/node_modules/passport/lib/strategies/session.js:75:10)
    at attempt (/overleaf/node_modules/passport/lib/middleware/authenticate.js:366:16)
    at authenticate (/overleaf/node_modules/passport/lib/middleware/authenticate.js:367:7)
    at Layer.handle [as handle_request] (/overleaf/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/overleaf/node_modules/express/lib/router/index.js:328:13)
    at /overleaf/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/overleaf/node_modules/express/lib/router/index.js:346:12)
    at next (/overleaf/node_modules/express/lib/router/index.js:280:10)
    at initialize (/overleaf/node_modules/passport/lib/middleware/initialize.js:53:5)
    at Layer.handle [as handle_request] (/overleaf/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/overleaf/node_modules/express/lib/router/index.js:328:13)
    at /overleaf/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/overleaf/node_modules/express/lib/router/index.js:346:12)
    at next (/overleaf/node_modules/express/lib/router/index.js:280:10)","info":{},"code":"EBADCSRFTOKEN"},"url":"/launchpad/register_admin","method":"POST","user":null,"msg":"invalid csrf","time":"2023-04-22T11:17:51.722Z","v":0}
```

**Comment by vctr-dng** [comment]
I fixed the issue by commenting (back ?) in bin/config/**variables.env** the lines : 
```
# SHARELATEX_BEHIND_PROXY=false
# SHARELATEX_SECURE_COOKIE=false
```
