### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by MickoLjudinicko** [overleaf/toolkit#166]
## Steps to Reproduce

1. Inside the overleaf-toolkit folder
2. Execute bin/upgrade
3. Execute bin/up

## Expected Behaviour

Expected to see the Overleaf Server run as normal. 

## Observed Behaviour

Unfortunately I get a 502 Bad Gateway instead, when trying to execute the UI from the browser.

## Context

Trying to upgrade the latex service to a newer instance.

## Technical Info

From all the docker containers, only serverlatex is the one whose status is constantly "Restarting".

The main concern is that basically all of the overleaf projects can't be migrated to a Full Project History.

Here's the log output:

> sharelatex    | > migrations
sharelatex    | > east migrate -t server-pro
sharelatex    | 
sharelatex    | Using default settings from /overleaf/services/web/config/settings.defaults.js
sharelatex    | Using settings from /etc/sharelatex/settings.server-pro.js
sharelatex    | Using sibling containers for sandboxed compiles
sharelatex    | Set UV_THREADPOOL_SIZE=16
mongo         | {"t":{"$date":"2023-06-02T11:53:33.158+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.22.0.4:40600","connectionId":30,"connectionCount":5}}
mongo         | {"t":{"$date":"2023-06-02T11:53:33.162+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn30","msg":"client metadata","attr":{"remote":"172.22.0.4:40600","client":"conn30","doc":{"driver":{"name":"nodejs|Mongoose","version":"4.13.0"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.10.0-19-cloud-amd64"},"platform":"Node.js v16.20.0, LE (unified)","version":"4.13.0|6.9.1","application":{"name":"web"}}}}
mongo         | {"t":{"$date":"2023-06-02T11:53:33.171+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.22.0.4:40608","connectionId":31,"connectionCount":6}}
mongo         | {"t":{"$date":"2023-06-02T11:53:33.175+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn31","msg":"client metadata","attr":{"remote":"172.22.0.4:40608","client":"conn31","doc":{"driver":{"name":"nodejs|Mongoose","version":"4.13.0"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.10.0-19-cloud-amd64"},"platform":"Node.js v16.20.0, LE (unified)","version":"4.13.0|6.9.1","application":{"name":"web"}}}}
mongo         | {"t":{"$date":"2023-06-02T11:53:33.265+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.22.0.4:40614","connectionId":32,"connectionCount":7}}
mongo         | {"t":{"$date":"2023-06-02T11:53:33.266+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn32","msg":"client metadata","attr":{"remote":"172.22.0.4:40614","client":"conn32","doc":{"driver":{"name":"nodejs|Mongoose","version":"4.13.0"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.10.0-19-cloud-amd64"},"platform":"Node.js v16.20.0, LE (unified)","version":"4.13.0|6.9.1","application":{"name":"web"}}}}
sharelatex    | Target migrations:
sharelatex    |         20230512100122_ensure_history_migration
sharelatex    | Migrate "20230512100122_ensure_history_migration"
sharelatex    | Error: Error during migrate "20230512100122_ensure_history_migration": Found 34 projects not migrated to Full Project History
sharelatex    |     at exports.migrate (/overleaf/services/web/migrations/20230512100122_ensure_history_migration.js:9:11)
sharelatex    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
sharelatex    |     at async /overleaf/node_modules/p-map/index.js:57:22
mongo         | {"t":{"$date":"2023-06-02T11:53:33.273+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn32","msg":"Connection ended","attr":{"remote":"172.22.0.4:40614","connectionId":32,"connectionCount":6}}
mongo         | {"t":{"$date":"2023-06-02T11:53:33.273+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn31","msg":"Connection ended","attr":{"remote":"172.22.0.4:40608","connectionId":31,"connectionCount":5}}
mongo         | {"t":{"$date":"2023-06-02T11:53:33.274+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn30","msg":"Connection ended","attr":{"remote":"172.22.0.4:40600","connectionId":30,"connectionCount":4}}
sharelatex    | npm ERR! Lifecycle script `migrations` failed with error: 
sharelatex    | npm ERR! Error: command failed 
sharelatex    | npm ERR!   in workspace: @overleaf/web 
sharelatex    | npm ERR!   at location: /overleaf/services/web 
sharelatex    | *** /etc/my_init.d/99_run_web_migrations.sh failed with status 1
sharelatex    | 
sharelatex    | *** Killing all processes...
sharelatex    | Jun  2 11:53:33 06079a95d78d syslog-ng[61]: syslog-ng shutting down; version='3.25.1'

Thanks in advance :).

**Comment by rpmcruz** [comment]
@MickoLjudinicko, I am getting the same error - were you able to work around this problem?

**Comment by mlevans0** [comment]
Hey there! As there hasn't been any recent comments or activity on this issue since July 21, 2023, we’re going to close it to keep our tracker focused on the most active and current issues/questions.

If you’re still experiencing this issue and would like to keep it open, please leave a comment to re-open. Thanks!
