### ISSUE TITLE
Deploying issues with docker compose file

### ISSUE THREAD

**Issue by Viking-1** [overleaf/toolkit#192]
I can't run overleaf with a docker compose file (attached):
[dockercompose.txt](https://github.com/overleaf/toolkit/files/12845591/dockercompose.txt)

Everything seems fine: overleaf, redis and mongo are running and mongo is also healthy. 
But:

`*** Killing all processes...
Oct  9 13:50:45 0e458a658ca4 syslog-ng[60]: syslog-ng shutting down; version='3.25.1'
*** Running /etc/my_init.d/00_make_sharelatex_data_dirs.sh...
*** Running /etc/my_init.d/00_regen_sharelatex_secrets.sh...
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/00_restore_site_status...
*** Running /etc/my_init.d/00_set_docker_host_ipaddress.sh...
*** Running /etc/my_init.d/01_nginx_config_template.sh...
Nginx: generating config file from template
Nginx: reloading config
 * Reloading nginx configuration nginx
   ...done.
*** Running /etc/my_init.d/10_delete_old_logs.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Oct  9 13:50:45 0e458a658ca4 syslog-ng[60]: syslog-ng starting up; version='3.25.1'
*** Running /etc/my_init.d/98_check_db_access.sh...
Checking can connect to mongo and redis
Using default settings from /overleaf/services/web/config/settings.defaults.js
Using settings from /etc/sharelatex/settings.js
Set UV_THREADPOOL_SIZE=16
Cannot connect to mongodb
MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
    at Connection.openUri (/overleaf/services/web/node_modules/mongoose/lib/connection.js:825:32)
    at /overleaf/services/web/node_modules/mongoose/lib/index.js:414:10
    at /overleaf/services/web/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/overleaf/services/web/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (/overleaf/services/web/node_modules/mongoose/lib/index.js:1288:10)
    at Mongoose.connect (/overleaf/services/web/node_modules/mongoose/lib/index.js:413:20)
    at Object.<anonymous> (/overleaf/services/web/app/src/infrastructure/Mongoose.js:19:36)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) { 'mongo:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}
*** /etc/my_init.d/98_check_db_access.sh failed with status 1
*** Killing all processes...`

I'm pretty sure, that this setup was running a while ago with the attached file. What am I missing here?

**Comment by mwelsch** [comment]
As mentioned in Issue #165 :

If you are using the Toolkit check [manually-setting-up-mongodb-as-a-replica-set](https://github.com/overleaf/overleaf/wiki/Release-Notes--4.x.x#manually-setting-up-mongodb-as-a-replica-set) -> you need to run `docker-compose exec -it mongo mongo`  and then the given command to initiate the replica set

**Comment by mwelsch** [comment]
So the reason why overleaf is not starting is this line of your log

```
Cannot connect to mongodb
```

I ran into this issue while upgrading the version, maybe you upgrading your version of overleaf is the cause of the same thing I described in #193 ? The docker image version of the sharelatex container is not specified in the `docker-compose` - file, so I cannot tell what version you're attemting to run

**Comment by Viking-1** [comment]
First: I use "image: sharelatex/sharelatex:latest"

I created the whole stack, connected to the mongo instance and added the replica command. After that, I've restarted sharelatex and thats it. 

Second: Now I found another issue. Maybe I forget or misunderstood something. Sharelatex gets another external IP with

```
        networks:
            outside:
                ipv4_address: 192.168.1.35

with:
networks:
    outside:
        external: true
        name: net
```

That leads to the above log.

So I tried it w/o the external IP I got this:
```
Feb  7 10:51:48 6c3f5cdcbf5e syslog-ng[60]: syslog-ng starting up; version='3.25.1'

*** Running /etc/my_init.d/98_check_db_access.sh...
Checking can connect to mongo and redis
Using default settings from /overleaf/services/web/config/settings.defaults.js
Using settings from /etc/sharelatex/settings.js
Set UV_THREADPOOL_SIZE=16
Mongodb is up.
Using default settings from /overleaf/services/web/config/settings.defaults.js
Using settings from /etc/sharelatex/settings.js
Set UV_THREADPOOL_SIZE=16
Redis is up.
All checks passed
*** Running /etc/my_init.d/99_run_web_migrations.sh...
Running migrations for server-ce
> migrations
> MONGO_SOCKET_TIMEOUT=0 east migrate -t server-ce
Using default settings from /overleaf/services/web/config/settings.defaults.js
Using settings from /etc/sharelatex/settings.js
Set UV_THREADPOOL_SIZE=16
Target migrations:
	20230512100122_ensure_history_migration
	20230817081910_back_fill_gitBridge_feature_server_pro
	20231031164732_drop_redundant_indexes
	20231101153447_partial_last_opened_index
	20231101191643_drop_unused_indexes
Migrate "20230512100122_ensure_history_migration"
Error: Error during migrate "20230512100122_ensure_history_migration": Found 2 projects not migrated to Full Project History
	at exports.migrate (/overleaf/services/web/migrations/20230512100122_ensure_history_migration.js:9:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /overleaf/node_modules/p-map/index.js:57:22
npm ERR! Lifecycle script `migrations` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @overleaf/web 
npm ERR!   at location: /overleaf/services/web 
*** /etc/my_init.d/99_run_web_migrations.sh failed with status 1
*** Killing all processes...

```

**Comment by mwelsch** [comment]
What does your network setup look like?

(You specified [external](https://docs.docker.com/compose/compose-file/06-networks/#external) and a [name](https://docs.docker.com/compose/compose-file/06-networks/#name) in the network area and assigned a dedicated [ipv4_adress](https://docs.docker.com/compose/compose-file/05-services/#ipv4_address-ipv6_address); additionally you [linked](https://docs.docker.com/compose/compose-file/05-services/#links) sharelatex to the other containers. I'm kinda confused how/via which way you intend your docker containers to communicate)

Maybe - unless you have (important) projects you cannot access - it is a good idea to use [the recommended way to get overleaf up and running](https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md)?

The error from the last point looks like some upgrade faild (#166 #179  ?) - maybe you can use the latest running version (via  `image: sharelatex/sharelatex:[your_latest_running_version]`) and export/backup your projects from there?

**Comment by mlevans0** [comment]
Hey there! As there hasn't been any recent comments or activity on this issue since Feb 7, 2024, we’re going to close it to keep our tracker focused on the most active and current issues/questions.

If you’re still experiencing this issue and would like to keep it open, please verify the issue is present on the latest version of Overleaf CE/Toolkit and leave a comment to re-open. Thanks!
