### ISSUE TITLE
Mongo instance doesn't support transactions when upgrading to 4.x.x

### ISSUE THREAD

**Issue by mwelsch** [overleaf/toolkit#193]
Hey, I'm in the process of upgrading my services. I had overleaf ~3.2 running and upgraded it to `3.5.13` + ran the history migration and cleanup scripts.

When changing config/version to `4.0.1` or `4.0.6` I get the following error log:

```
mongo       | 2023-10-21T12:48:00.794+0000 I NETWORK  [conn10] received client metadata from 172.28.0.6:33180 conn10: { driver: { name: "nodejs|Mongoose", version: "4.13.0" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "6.1.0-7-amd64" }, platform: "Node.js v16.20.1, LE (unified)", version: "4.13.0|6.9.1", application: { name: "web" } }
sharelatex  | Mongo instance doesn't support transactions
sharelatex  | MongoServerError: Transactions are only supported in featureCompatibilityVersion 4.0. See http://dochub.mongodb.org/core/4.0-feature-compatibility for more information.
sharelatex  |     at Connection.onMessage (/overleaf/services/web/node_modules/mongodb/lib/cmap/connection.js:227:30)
sharelatex  |     at MessageStream.<anonymous> (/overleaf/services/web/node_modules/mongodb/lib/cmap/connection.js:60:60)
sharelatex  |     at MessageStream.emit (node:events:513:28)
sharelatex  |     at processIncomingData (/overleaf/services/web/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
sharelatex  |     at MessageStream._write (/overleaf/services/web/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
sharelatex  |     at writeOrBuffer (node:internal/streams/writable:391:12)
sharelatex  |     at _write (node:internal/streams/writable:332:10)
sharelatex  |     at MessageStream.Writable.write (node:internal/streams/writable:336:10)
sharelatex  |     at Socket.ondata (node:internal/streams/readable:754:22)
sharelatex  |     at Socket.emit (node:events:513:28) {
sharelatex  |   operationTime: new Timestamp({ t: 1697892477, i: 1 }),
sharelatex  |   ok: 0,
sharelatex  |   code: 50773,
sharelatex  |   codeName: 'Location50773',
sharelatex  |   '$clusterTime': {
sharelatex  |     clusterTime: new Timestamp({ t: 1697892477, i: 1 }),
sharelatex  |     signature: {
sharelatex  |       hash: new Binary(Buffer.from("0000000000000000000000000000000000000000", "hex"), 0),
sharelatex  |       keyId: 0
sharelatex  |     }
sharelatex  |   },
sharelatex  |   [Symbol(errorLabels)]: Set(0) {}
sharelatex  | }
mongo       | 2023-10-21T12:48:00.993+0000 I NETWORK  [conn10] end connection 172.28.0.6:33180 (3 connections now open)
```

[This](https://stackoverflow.com/questions/62349032/requirements-for-using-mongodb-transactions) post suggests that the wiredTrigger engine and replica sets need to be used, both seem to be the case as `docker logs mongo` suggests:

```
2023-10-21T12:47:27.991+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true }, replication: { replSet: "overleaf" } }
2023-10-21T12:47:27.994+0000 I STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2023-10-21T12:47:27.994+0000 I STORAGE  [initandlisten] 
2023-10-21T12:47:27.994+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2023-10-21T12:47:27.994+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2023-10-21T12:47:27.994+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3457M,cache_overflow=(file_max=0M),session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2023-10-21T12:47:33.404+0000 I STORAGE  [initandlisten] WiredTiger message [1697892453:404951][1:0x7fb7d18a3a80], txn-recover: Main recovery loop: starting at 2596/896 to 2597/256
2023-10-21T12:47:33.891+0000 I STORAGE  [initandlisten] WiredTiger message [1697892453:891854][1:0x7fb7d18a3a80], txn-recover: Recovering log 2596 through 2597
2023-10-21T12:47:34.293+0000 I STORAGE  [initandlisten] WiredTiger message [1697892454:293811][1:0x7fb7d18a3a80], txn-recover: Recovering log 2597 through 2597
2023-10-21T12:47:34.895+0000 I STORAGE  [initandlisten] WiredTiger message [1697892454:895658][1:0x7fb7d18a3a80], txn-recover: Set global recovery timestamp: 0
2023-10-21T12:47:35.302+0000 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
```

Running `rs.initiate({ _id: "overleaf", members: [ { _id: 0, host: "mongo:27017" } ] })` as suggested in #165 just tells me that the replica set already exists
```
overleaf:PRIMARY> rs.initiate({ _id: "overleaf", members: [ { _id: 0, host: "mongo:27017" } ] })
{
	"operationTime" : Timestamp(1697892737, 1),
	"ok" : 0,
	"errmsg" : "already initialized",
	"code" : 23,
	"codeName" : "AlreadyInitialized",
	"$clusterTime" : {
		"clusterTime" : Timestamp(1697892737, 1),
		"signature" : {
			"hash" : BinData(0,"AAAAAAAAAAAAAAAAAAAAAAAAAAA="),
			"keyId" : NumberLong(0)
		}
	}
}
```

I tried t0:
- shut all containers down, delete them with `docker system prune -a` and recreate them --> same issue
- delete my `data` directory and replace it with the backup from before upgrading. Ran the upgrades again and had the same issue

Downgrading to `3.5.13` for now as this version works

**Comment by sanchirico** [comment]
Thanks for the detailed issue. I ran into the same error and version 3.5.13 saved the day. It would be nice to see a resolution here.

**Comment by loockeeer** [comment]
Hi, same issue here too :/

**Comment by ericjmcd** [comment]
Any update on this issue?

**Comment by mlevans0** [comment]
Hey there! As there hasn't been any recent comments or activity on this issue since June 6, 2024, we’re going to close it to keep our tracker focused on the most active and current issues/questions.

If you’re still experiencing this issue and would like to keep it open, please verify the issue is present on the latest version of Overleaf CE/Toolkit and leave a comment to re-open. Thanks!
