### ISSUE TITLE
DockerException

### ISSUE THREAD

**Issue by slowbrew** [overleaf/toolkit#41]
```
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 80, in main
  File "compose\cli\main.py", line 189, in perform_command
  File "compose\cli\command.py", line 60, in project_from_options
  File "compose\cli\command.py", line 152, in get_project
  File "compose\cli\docker_client.py", line 41, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "docker\api\client.py", line 197, in __init__
  File "docker\api\client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
[16500] Failed to execute script docker-compose
```

**Comment by slowbrew** [comment]
All good up to line 84 of the quickstart -- then bin/up fails

**Comment by ShaneKilkelly** [comment]
How very strange. Could you run `bin/doctor` and paste the output here? Thanks!

**Comment by mlevans0** [comment]
Hey there! As there hasn't been any recent comments or activity on this issue for quite a while, we’re going to close it to keep our tracker focused on the most active and current issues/questions.

If you’re still experiencing this issue and would like to keep it open, please verify the issue is present on the latest version of Overleaf CE/Toolkit and leave a comment to re-open. Thanks!
